import { makeStyles } from '@material-ui/core/styles';

export const useStylesFM = makeStyles((styles) => ({
	containerFM: {
		position: 'relative',
		// height: '440px',
		width: '80%',
	},
	buttonNext: {
		marginRight: styles.spacing(1),
		textTransform: 'none',
		width: 115,
	},
	buttonBack: {
		marginRight: styles.spacing(40),
		textTransform: 'none',
	},
	input: {
		display: 'flex',
		width: '100%',
		margin: '8px 0',
		textAlign: 'center',
		alignItems: 'center',
		justifyContent: 'center',
	},
	row: {
		display: 'flex',
		width: '100%',
		justifyContent: 'space-between',
	},
	buttonStep4: {
		textTransform: 'none',
		width: '45%',
		marginLeft: styles.spacing(0),
		marginBottom: styles.spacing(0.5),
		padding: 0,
		height: '100%',
	},
	inputLine3: {
		width: '100%',
		textAlign: 'center',
		alignSelf: 'center',
		display: 'grid',
		gridColumnGap: '1%',
		gridTemplateColumns: '1fr 1fr',
	},
	inputM: {
		display: 'flex',
		width: '50%',
		textAlign: 'center',
		alignSelf: 'center',
		// marginRight: styles.spacing(0.5),
	},
	inputC: {
		display: 'flex',
		width: '50%',
		textAlign: 'center',
		alignSelf: 'center',
		// marginLeft: styles.spacing(0.5),
	},
	inputN: {
		display: 'flex',
		width: '50%',
		textAlign: 'center',
		alignSelf: 'center',
		// marginLeft: styles.spacing(0.5),
	},
	inputMP: {
		display: 'flex',
		width: '25%',
		textAlign: 'center',
		alignSelf: 'center',
		marginRight: '2%',
	},
	inputNP: {
		display: 'flex',
		width: '100%',
		textAlign: 'center',
		alignSelf: 'center',
		marginLeft: styles.spacing(0.5),
	},
	inputA: {
		display: 'flex',
		width: '100%',
		textAlign: 'center',
		alignSelf: 'center',
	},
	inputTipoId: {
		width: '15%',
		margin: 0,
		marginRight: styles.spacing(1.5),
	},
	inputDoc: {
		width: '60%',
	},
	inputText: {
		width: '100%',
	},
	inputTextLeft: {
		width: '100%',
		marginRight: '2%',
	},
	imgIdent: {
		padding: '0',
		textTransform: 'none',
		width: '35%',
		height: '100%',
	},
	imgContributor: {
		textTransform: 'none',
		width: '50%',
		marginTop: styles.spacing(1),
		marginBottom: styles.spacing(1),
		marginLeft: styles.spacing(1),
		height: '100%',
	},
	imgStep1: {
		textTransform: 'none',
		width: '30%',
		marginLeft: styles.spacing(0),
		marginBottom: styles.spacing(0.5),
		padding: 0,
		height: '100%',
	},
	buttonFixed: {
		position: 'fixed',
		display: 'flex',
		justifyContent: 'center',
		width: '100%',
		bottom: '2rem',
	},
}));
